// Expo config plugin for live-timer.
// Handles Info.plist (Live Activities + audio background mode), the
// Android manifest (foreground service + permissions), and Xcode build
// settings to keep the widget extension's CFBundleVersion in sync with
// the parent app.
//
// The widget extension target itself is generated by @bacons/apple-targets
// from targets/<name>/ in the host app — this plugin doesn't create the
// target. But @bacons/apple-targets only syncs MARKETING_VERSION across
// targets, not CURRENT_PROJECT_VERSION. With EAS autoIncrement bumping
// the parent app's build number server-side, the widget keeps its
// default CFBundleVersion of "1" and fastlane rejects the build:
//   "The CFBundleVersion of an app extension ('1') must match that
//    of its containing parent app ('27')."
// See expo/expo#43740. The Xcode-project mod below patches every native
// target's build settings so the widget always matches the parent.

const {
  withInfoPlist,
  withAndroidManifest,
  withXcodeProject,
} = require('@expo/config-plugins');

function withLiveTimerInfoPlist(config) {
  return withInfoPlist(config, (cfg) => {
    cfg.modResults.NSSupportsLiveActivities = true;
    cfg.modResults.NSSupportsLiveActivitiesFrequentUpdates = true;

    const existing = Array.isArray(cfg.modResults.UIBackgroundModes)
      ? cfg.modResults.UIBackgroundModes
      : [];
    if (!existing.includes('audio')) {
      cfg.modResults.UIBackgroundModes = [...existing, 'audio'];
    }
    return cfg;
  });
}

function withLiveTimerAndroidManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) return cfg;

    const services = app.service ?? (app.service = []);
    const exists = services.some(
      (s) => s.$?.['android:name'] === 'expo.modules.livetimer.LiveTimerService'
    );
    if (!exists) {
      services.push({
        $: {
          'android:name': 'expo.modules.livetimer.LiveTimerService',
          'android:foregroundServiceType': 'mediaPlayback',
          'android:exported': 'false',
        },
      });
    }

    const receivers = app.receiver ?? (app.receiver = []);
    const receiverExists = receivers.some(
      (r) => r.$?.['android:name'] === 'expo.modules.livetimer.LiveTimerActionReceiver'
    );
    if (!receiverExists) {
      receivers.push({
        $: {
          'android:name': 'expo.modules.livetimer.LiveTimerActionReceiver',
          'android:exported': 'false',
        },
      });
    }

    const manifest = cfg.modResults.manifest;
    const perms = manifest['uses-permission'] ?? (manifest['uses-permission'] = []);
    const required = [
      'android.permission.FOREGROUND_SERVICE',
      'android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK',
      'android.permission.POST_NOTIFICATIONS',
      'android.permission.WAKE_LOCK',
    ];
    for (const name of required) {
      if (!perms.some((p) => p.$?.['android:name'] === name)) {
        perms.push({ $: { 'android:name': name } });
      }
    }

    return cfg;
  });
}

function withLiveTimerSyncedTargetVersions(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const buildNumber = String(cfg.ios?.buildNumber ?? '1');
    const marketingVersion = String(cfg.version ?? '1.0.0');

    const buildConfigs = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const buildSettings = buildConfigs[key]?.buildSettings;
      // Skip non-target configs (project-level, etc.) — they don't have
      // a bundle id and don't need version stamps.
      if (!buildSettings || !buildSettings.PRODUCT_BUNDLE_IDENTIFIER) continue;
      buildSettings.CURRENT_PROJECT_VERSION = buildNumber;
      buildSettings.MARKETING_VERSION = marketingVersion;
    }

    return cfg;
  });
}

const withLiveTimer = (config) => {
  config = withLiveTimerInfoPlist(config);
  config = withLiveTimerAndroidManifest(config);
  config = withLiveTimerSyncedTargetVersions(config);
  return config;
};

module.exports = withLiveTimer;
