#!/usr/bin/env node
/**
 * compile-flow.mjs — compile a copy-free journey into a Maestro flow.
 *
 * The whole point of this layer: Maestro flows break constantly because they
 * hard-code visible copy (`tapOn: "Greece.*"`). When the app's copy or screens
 * change, the flow silently targets nothing. So we DON'T hand-write the flow.
 * We write two small, stable files and GENERATE the flow from them:
 *
 *   qa/selectors.json  — semantic anchors. One place for every brittle string.
 *                        Each anchor resolves to a Maestro selector: a `testID`
 *                        (copy-proof — survives any wording change) or `text`
 *                        (a Maestro regex matching visible text OR the a11y
 *                        label). When copy moves, you fix ONE anchor here, not
 *                        N scattered flow lines — and the self-healer
 *                        (heal.mjs) can rewrite it for you from the live screen.
 *
 *   qa/journey.json    — the traversal itself, in terms of @anchor keys, never
 *                        raw copy. This is the real source of truth for "what
 *                        the screenshot run does". Platform-agnostic.
 *
 * Output: qa/flows/mobile.yaml — a build artifact, marked DO NOT EDIT. Because
 * it's regenerated, it can never drift from intent; lint-flows.mjs --check
 * fails CI if a committed yaml doesn't match a fresh compile.
 *
 * Usage:
 *   node scripts/qa/compile-flow.mjs [app-dir]        # write qa/flows/mobile.yaml
 *   node scripts/qa/compile-flow.mjs [app-dir] --check  # exit 1 if on-disk yaml is stale
 *   node scripts/qa/compile-flow.mjs [app-dir] --stdout # print, don't write
 *
 * STORE footgun (memory feedback): Maestro's flow-level `env:` block out-ranks
 * the `--env=` CLI flag, so a baked `env: STORE: ios` silently wins on the wrong
 * platform and writes captures to the wrong store dir. We therefore emit NO
 * flow-level env — the capture path uses `${STORE}`, supplied per-run via
 * `--env=STORE=<store>`.
 */

import fs from 'node:fs';
import path from 'node:path';

export const GENERATED_HEADER = (appDir) =>
  `# GENERATED by scripts/qa/compile-flow.mjs — DO NOT EDIT.\n` +
  `# Source of truth: qa/journey.json + qa/selectors.json.\n` +
  `# Re-generate:  node scripts/qa/compile-flow.mjs\n` +
  `# Validate:     node scripts/qa/lint-flows.mjs   (fails if this file is stale)\n` +
  `#\n` +
  `# STORE is supplied per-run via --env=STORE=<store>. There is deliberately NO\n` +
  `# flow-level env: block — a baked default out-ranks the CLI flag and writes\n` +
  `# captures to the wrong store dir (hard-won; see runbooks/qa-capture.md).\n`;

/** Quote a string for single-line YAML double-quoted scalar. */
function yq(s) {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/**
 * Resolve a journey token to a Maestro selector object literal.
 * `@key` looks up qa/selectors.json; a bare string is treated as literal text.
 * Returns { kind: 'id'|'text', value } — testID always wins when present.
 */
export function resolveSelector(token, anchors, ctx) {
  if (typeof token !== 'string') {
    throw new Error(`${ctx}: selector must be a string, got ${JSON.stringify(token)}`);
  }
  if (token.startsWith('@')) {
    const key = token.slice(1);
    const a = anchors[key];
    if (!a) throw new Error(`${ctx}: unknown anchor "@${key}" (not in qa/selectors.json)`);
    if (a.testID) return { kind: 'id', value: a.testID };
    if (a.text) return { kind: 'text', value: a.text };
    throw new Error(`${ctx}: anchor "@${key}" has neither testID nor text`);
  }
  return { kind: 'text', value: token };
}

/** Render a resolved selector as an inline Maestro selector map: `{ id: "x" }`. */
function selInline(sel) {
  return `{ ${sel.kind}: ${yq(sel.value)} }`;
}

/**
 * Map a friendly orientation token to a Maestro setOrientation value. Maestro
 * 2.x accepts PORTRAIT / LANDSCAPE_LEFT / LANDSCAPE_RIGHT / UPSIDE_DOWN (it
 * rejects a bare "LANDSCAPE"). "landscape" -> LANDSCAPE_LEFT by convention.
 */
export function maestroOrientation(token) {
  const t = String(token || '').toLowerCase().replace(/[\s-]+/g, '_');
  const map = {
    portrait: 'PORTRAIT',
    landscape: 'LANDSCAPE_LEFT',
    landscape_left: 'LANDSCAPE_LEFT',
    landscape_right: 'LANDSCAPE_RIGHT',
    upside_down: 'UPSIDE_DOWN',
  };
  const v = map[t];
  if (!v) throw new Error(`unknown orientation "${token}" (use portrait | landscape | landscape_right | upside_down)`);
  return v;
}

/**
 * Compile a journey object into Maestro flow YAML text.
 * Pure (no I/O) so lint/tests can call it directly.
 */
export function compileJourney(journey, selectors, appDir = '.', opts = {}) {
  const anchors = (selectors && selectors.anchors) || {};
  if (!journey.appId) throw new Error('journey.json: missing "appId"');
  const steps = journey.steps || [];
  if (!Array.isArray(steps)) throw new Error('journey.json: "steps" must be an array');

  const out = [];
  out.push(GENERATED_HEADER(appDir));
  out.push(`appId: ${journey.appId}`);
  out.push('---');

  // Launch is always first. clearState defaults true (deterministic boot).
  const clear = journey.clearState !== false;
  out.push('- launchApp:');
  out.push(`    clearState: ${clear ? 'true' : 'false'}`);

  // Cell-level orientation (P10 device matrix): capture.mjs passes the cell's
  // orientation through to here so the rotation drives the OS deterministically
  // on BOTH platforms (Maestro setOrientation), rather than via brittle
  // simctl/adb rotation. Injected right after launch, before the journey runs.
  // Portrait is the default and needs no injection.
  if (opts.orientation && String(opts.orientation).toLowerCase() !== 'portrait') {
    out.push(`- setOrientation: ${maestroOrientation(opts.orientation)}`);
  }

  // Optional diagnostic: settle, then snapshot whatever rendered. If a later
  // assertion fails, this artifact shows what the app actually drew (splash,
  // error, blank) instead of leaving you blind. Mirrors FWT's proven flow.
  if (journey.diagnosticLaunchShot) {
    const settle = journey.settleMs || 8000;
    out.push('- waitForAnimationToEnd:');
    out.push(`    timeout: ${settle}`);
    out.push('- takeScreenshot: qa/captures/${STORE}/00-launch');
  }

  steps.forEach((step, i) => {
    const ctx = `journey.steps[${i}]`;
    const keys = Object.keys(step);
    // A step is one action object. The verb is the first recognized key.
    if ('waitFor' in step) {
      const sel = resolveSelector(step.waitFor, anchors, ctx);
      out.push('- extendedWaitUntil:');
      out.push(`    visible: ${selInline(sel)}`);
      out.push(`    timeout: ${step.timeout || 15000}`);
    } else if ('assert' in step) {
      const sel = resolveSelector(step.assert, anchors, ctx);
      out.push(`- assertVisible: ${selInline(sel)}`);
    } else if ('assertNot' in step) {
      // Tier 2 OUTCOME assertion: prove an element is GONE after an action —
      // the seeded item after a delete, an error banner that must not appear,
      // a cleared field. `assert` proves a screen rendered (navigation sanity);
      // `assertNot` proves the flow produced the right result. This is the
      // verb that turns the screenshot traversal into a behavioral e2e test.
      const sel = resolveSelector(step.assertNot, anchors, ctx);
      out.push(`- assertNotVisible: ${selInline(sel)}`);
    } else if ('tap' in step) {
      const sel = resolveSelector(step.tap, anchors, ctx);
      out.push(`- tapOn: ${selInline(sel)}`);
    } else if ('tapPoint' in step) {
      // For elements outside the a11y tree (e.g. RN <Modal> content on iOS) —
      // tap a percentage point. Use sparingly; prefer anchors.
      out.push(`- tapOn:`);
      out.push(`    point: ${yq(step.tapPoint)}`);
    } else if ('type' in step) {
      // Always literal text — never an anchor.
      out.push(`- inputText: ${yq(step.type)}`);
    } else if ('pressKey' in step) {
      out.push(`- pressKey: ${step.pressKey}`);
    } else if ('hideKeyboard' in step) {
      out.push('- hideKeyboard');
    } else if ('swipe' in step) {
      const dir = step.swipe; // "up" | "down" | "left" | "right"
      out.push('- swipe:');
      out.push(`    direction: ${String(dir).toUpperCase()}`);
    } else if ('scrollUntilVisible' in step) {
      // Idempotent reveal: scroll (default DOWN) until the anchor is on screen.
      // A NO-OP when the element is already visible, so it can't regress captures
      // on larger devices — only the smallest screens (e.g. iPhone SE) actually
      // scroll. Use before a `tap` whose target can sit below the fold on the
      // smallest device. Optional `scrollDirection: "up"|"down"|"left"|"right"`.
      const sel = resolveSelector(step.scrollUntilVisible, anchors, ctx);
      out.push('- scrollUntilVisible:');
      out.push(`    element: ${selInline(sel)}`);
      out.push(`    direction: ${String(step.scrollDirection || 'DOWN').toUpperCase()}`);
      // Maestro defaults to requiring the element 100% on-screen. On a short
      // device a target in the last row can sit partly under a pinned bottom CTA
      // and never reach 100%, so allow a lower threshold (the element is still
      // tappable when partially visible). `scrollVisibility: <1-100>`.
      if (step.scrollVisibility != null) {
        out.push(`    visibilityPercentage: ${Number(step.scrollVisibility)}`);
      }
    } else if ('wait' in step) {
      out.push('- waitForAnimationToEnd:');
      out.push(`    timeout: ${step.wait}`);
    } else if ('background' in step) {
      // Resilience probe (canon § Resilience): send the app to the background.
      // Pair with a `relaunch` step + an `assert` to prove mid-task state
      // survives a backgrounding. `background: <ms>` also waits after.
      out.push('- pressKey: Home');
      if (typeof step.background === 'number') {
        out.push('- waitForAnimationToEnd:');
        out.push(`    timeout: ${step.background}`);
      }
    } else if ('stopApp' in step) {
      // Resilience probe: process kill. Follow with `relaunch` (keepState) +
      // `assert` to prove persisted state restores after a full termination —
      // the iOS/Android "OS killed the suspended app" case canon requires.
      out.push('- stopApp');
    } else if ('relaunch' in step) {
      // Relaunch WITHOUT clearing state by default (keepState) — the whole point
      // of a resilience probe is that data persisted to disk comes back.
      // `relaunch: "fresh"` clears state (a cold first-run).
      const keep = step.relaunch !== 'fresh' && step.relaunch?.keepState !== false;
      out.push('- launchApp:');
      out.push(`    clearState: ${keep ? 'false' : 'true'}`);
    } else if ('rotate' in step) {
      // In-flow rotation round-trip (canon § Resilience: orientation changes
      // don't lose state). Distinct from the cell-level orientation axis — use
      // this to rotate mid-journey then assert the user stayed in place.
      out.push(`- setOrientation: ${maestroOrientation(step.rotate)}`);
    } else if ('killApp' in step) {
      // Chaos probe (T4 state-survival): REAL system-initiated process death —
      // NOT the graceful `stopApp`. On Android `killApp` issues an actual
      // process kill (the "OS reclaimed a backgrounded app mid-write" regime
      // Josh's hardest bug reports came from). iOS has no true force-kill
      // through Maestro's driver, so we alias to `stopApp` (the closest
      // available termination) and say so. One YAML runs BOTH platforms, so we
      // branch with runFlow/when:platform rather than emit a bare command that
      // silently behaves differently per OS. Follow with `relaunch` (keepState)
      // + an outcome `assert` to prove state persisted before the kill survived.
      out.push('# killApp: real process death on Android; stopApp alias on iOS');
      out.push('# (no true force-kill via the iOS XCTest driver). See runbooks/testing-net.md § chaos net.');
      out.push('- runFlow:');
      out.push('    when:');
      out.push('      platform: Android');
      out.push('    commands:');
      out.push('      - killApp');
      out.push('- runFlow:');
      out.push('    when:');
      out.push('      platform: iOS');
      out.push('    commands:');
      out.push('      - stopApp');
    } else if ('screenshot' in step) {
      out.push('- takeScreenshot: qa/captures/${STORE}/' + step.screenshot);
    } else {
      throw new Error(`${ctx}: unrecognized step ${JSON.stringify(keys)}`);
    }
  });

  return out.join('\n') + '\n';
}

/**
 * The state-survival flow (T4 chaos net) is a SEPARATE compiled artifact from
 * the screenshot/Tier-2 traversal — deliberately, because it must run in the
 * FULL profile + nightly, NOT per-PR (the per-PR CI runs only mobile.yaml).
 * It's authored as an optional top-level `survival` block in journey.json:
 *
 *   "survival": { "$comment": "...", "clearState": true, "steps": [ ... ] }
 *
 * The sequence is: mutate → killApp → relaunch(keepState) → assert the outcome
 * SURVIVED (an intent waypoint, not a pixel). This helper projects that block
 * into a normal journey object so compileJourney can render it verbatim.
 * Returns null when the app declares no survival block.
 */
export function survivalJourney(journey) {
  if (!journey || !journey.survival) return null;
  const s = journey.survival;
  if (!Array.isArray(s.steps)) throw new Error('journey.json: "survival.steps" must be an array');
  return {
    appId: journey.appId,
    // A survival flow always starts from a clean, seeded boot (clearState:true)
    // so the mutation it makes is the ONLY off-seed datum — then proves THAT
    // survives the kill. Never a diagnostic launch shot (it's a behavioral run,
    // not a capture run).
    clearState: s.clearState !== false,
    steps: s.steps,
  };
}

// ---------- CLI ----------

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function main() {
  const args = process.argv.slice(2);
  const flags = new Set(args.filter((a) => a.startsWith('--')));
  const valueOf = (name) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : null; };
  const VALUE_FLAGS = new Set(['--orientation']);
  const appDir = path.resolve(args.find((a, i) => !a.startsWith('--') && !VALUE_FLAGS.has(args[i - 1])) || process.cwd());
  // Cell-level orientation for the device matrix (capture.mjs --orientation).
  // Default portrait => no injection => identical to the canonical artifact, so
  // lint/freshness stays stable; only landscape/etc. cells inject a rotation.
  const orientation = valueOf('--orientation') || 'portrait';

  const journeyPath = path.join(appDir, 'qa', 'journey.json');
  const selectorsPath = path.join(appDir, 'qa', 'selectors.json');
  const outPath = path.join(appDir, 'qa', 'flows', 'mobile.yaml');
  const survivalPath = path.join(appDir, 'qa', 'flows', 'state-survival.yaml');

  if (!fs.existsSync(journeyPath)) {
    console.error(`No qa/journey.json in ${appDir}. Copy qa/journey.example.json to start.`);
    process.exit(1);
  }
  const journey = readJson(journeyPath);
  const selectors = fs.existsSync(selectorsPath) ? readJson(selectorsPath) : { anchors: {} };

  let yaml, survivalYaml;
  try {
    yaml = compileJourney(journey, selectors, appDir, { orientation });
    // The state-survival flow (T4) uses no orientation axis — it's a behavioral
    // run, not a per-cell capture — so it compiles once, canonically.
    const sj = survivalJourney(journey);
    survivalYaml = sj ? compileJourney(sj, selectors, appDir) : null;
  } catch (e) {
    console.error(`compile-flow: ${e.message}`);
    process.exit(1);
  }

  if (flags.has('--stdout')) {
    process.stdout.write(flags.has('--survival') && survivalYaml ? survivalYaml : yaml);
    return;
  }

  if (flags.has('--check')) {
    const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
    if (current !== yaml) {
      console.error(`qa/flows/mobile.yaml is STALE — re-run: node scripts/qa/compile-flow.mjs`);
      process.exit(1);
    }
    if (survivalYaml != null) {
      const curSurv = fs.existsSync(survivalPath) ? fs.readFileSync(survivalPath, 'utf8') : '';
      if (curSurv !== survivalYaml) {
        console.error(`qa/flows/state-survival.yaml is STALE — re-run: node scripts/qa/compile-flow.mjs`);
        process.exit(1);
      }
    }
    console.log('qa/flows/mobile.yaml is up to date.' + (survivalYaml != null ? ' state-survival.yaml too.' : ''));
    return;
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, yaml);
  console.log(`Wrote ${path.relative(appDir, outPath)} (${journey.steps?.length || 0} steps).`);
  if (survivalYaml != null) {
    fs.writeFileSync(survivalPath, survivalYaml);
    console.log(`Wrote ${path.relative(appDir, survivalPath)} (${journey.survival.steps?.length || 0} survival steps).`);
  }
}

// Only run as CLI when invoked directly, not when imported by lint/heal/tests.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
