// Canonical Josh Approved Acknowledgements screen.
// Source: josh-approved-factory/templates/credits/Credits.tsx
// Pairs with src/data/credits.ts (generated by generate-credits.mjs).
// See README.md for canonical rules and wiring.
//
// Imports from '../theme' — every Josh Approved app has the design-system
// tokens synced into src/theme/. Don't reimplement styling here; the screen
// inherits from the design system so all apps look like siblings.

import React from 'react';
import {
  View,
  Text,
  Pressable,
  ScrollView,
  StyleSheet,
  Linking,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ChevronLeft, ExternalLink } from 'lucide-react-native';
import { CREDITS, CREDITS_INTRO } from '../data/credits';
import {
  useTheme,
  fontFamily,
  space,
  radius,
  type as t,
  hairline,
  tracking,
  Colors,
} from '../theme';

interface Props {
  onBack: () => void;
}

export default function Credits({ onBack }: Props) {
  const { c } = useTheme();
  const s = makeStyles(c);

  return (
    <SafeAreaView style={s.container}>
      <View style={s.header}>
        <Pressable
          onPress={onBack}
          hitSlop={8}
          accessibilityLabel="Back"
          accessibilityRole="button"
          style={({ pressed }) => [s.headerSide, pressed && s.pressed]}
        >
          <ChevronLeft size={22} color={c.fg} strokeWidth={1.5} />
          <Text style={s.headerBackText}>Back</Text>
        </Pressable>
        <Text style={s.headerTitle} accessibilityRole="header">
          Acknowledgements
        </Text>
        <View style={s.headerSide} />
      </View>

      <ScrollView contentContainerStyle={s.scroll}>
        <Text style={s.intro}>{CREDITS_INTRO}</Text>

        <View style={s.card}>
          {CREDITS.map((entry, idx) => (
            <Pressable
              key={`${entry.name}-${idx}`}
              style={({ pressed }) => [
                s.row,
                idx > 0 && s.rowBorder,
                pressed && s.rowPressed,
              ]}
              onPress={() => Linking.openURL(entry.url).catch(() => {})}
              accessibilityRole="link"
              accessibilityLabel={`${entry.name}, ${entry.license}`}
              accessibilityHint="Opens the project page in your browser"
            >
              <View style={s.rowMain}>
                <Text style={s.name}>{entry.name}</Text>
                <View style={s.metaRow}>
                  {entry.version ? (
                    <Text style={s.version}>{entry.version}</Text>
                  ) : null}
                  <Text style={s.license}>{entry.license}</Text>
                </View>
              </View>
              <ExternalLink
                size={16}
                color={c.fgSubtle}
                strokeWidth={1.5}
              />
            </Pressable>
          ))}
        </View>

        <Text style={s.footnote}>
          Full license texts live in each project's repository.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

function makeStyles(c: Colors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: space.s5,
      paddingVertical: space.s3,
      borderBottomWidth: hairline,
      borderBottomColor: c.hairline,
    },
    headerSide: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: space.s1,
    },
    pressed: { opacity: 0.7 },
    headerBackText: { ...t.base, color: c.fg, fontFamily: fontFamily.sans },
    headerTitle: {
      ...t.base,
      color: c.fg,
      fontFamily: fontFamily.sansSemibold,
      textAlign: 'center',
    },

    scroll: { padding: space.s5, paddingBottom: space.s8 },
    intro: {
      ...t.sm,
      color: c.fgMuted,
      fontFamily: fontFamily.sans,
      lineHeight: 20,
      marginBottom: space.s5,
      paddingHorizontal: space.s1,
    },

    card: {
      backgroundColor: c.bgElevated,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: c.hairline,
      overflow: 'hidden',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: space.s5,
      paddingVertical: space.s4,
      gap: space.s3,
    },
    rowBorder: { borderTopWidth: hairline, borderTopColor: c.hairline },
    rowPressed: { backgroundColor: c.bg },
    rowMain: { flex: 1 },
    name: {
      ...t.sm,
      color: c.fg,
      fontFamily: fontFamily.sansMedium,
    },
    metaRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: space.s2,
      marginTop: 2,
    },
    version: {
      ...t.xs,
      color: c.fgSubtle,
      fontFamily: fontFamily.mono,
    },
    license: {
      ...t.xs,
      color: c.fgMuted,
      fontFamily: fontFamily.sans,
      letterSpacing: tracking.wide,
      textTransform: 'uppercase',
    },

    footnote: {
      ...t.xs,
      color: c.fgSubtle,
      fontFamily: fontFamily.sans,
      textAlign: 'center',
      marginTop: space.s5,
      paddingHorizontal: space.s5,
    },
  });
}
