// Generated by josh-approved-factory/scripts/generate-credits.mjs.
// Source: credits-config.json + package.json + node_modules.
// Do not edit by hand — re-run the generator after dep updates.

export interface CreditEntry {
  name: string;
  version: string;
  license: string;
  url: string;
}

export const CREDITS_INTRO = "Free Workout Timer is built on the work of these open-source projects.";

export const CREDITS: CreditEntry[] = [
  {
    "name": "React Native",
    "version": "0.83.6",
    "license": "MIT",
    "url": "https://reactnative.dev/"
  },
  {
    "name": "Expo",
    "version": "55.0.18",
    "license": "MIT",
    "url": "https://github.com/expo/expo/tree/main/packages/expo"
  },
  {
    "name": "React Navigation",
    "version": "7.2.2",
    "license": "MIT",
    "url": "https://reactnavigation.org"
  },
  {
    "name": "react-native-svg",
    "version": "15.15.3",
    "license": "MIT",
    "url": "https://github.com/react-native-community/react-native-svg"
  },
  {
    "name": "Slider",
    "version": "5.1.2",
    "license": "MIT",
    "url": "https://github.com/callstack/react-native-slider#readme"
  },
  {
    "name": "AsyncStorage",
    "version": "2.2.0",
    "license": "MIT",
    "url": "https://github.com/react-native-async-storage/async-storage#readme"
  },
  {
    "name": "Lucide",
    "version": "1.14.0",
    "license": "ISC",
    "url": "https://lucide.dev"
  },
  {
    "name": "IBM Plex",
    "version": "",
    "license": "OFL 1.1",
    "url": "https://www.ibm.com/plex/"
  }
];
